function fib(num) {
	// initialize looping variable here. no recursion used to generate the fibonacci numbers
	var i, fibArr = [0,1];
	// sanity check for incorrect function input from the user. this can be replaced when incorporated into DOM elements
	if (typeof(num) == 'string' || num === '') {
		return "Use integer inputs for this function"
	} else {
		// any numeric input less than 3
		if (num < 3) {
			return "The Fibonacci sequence starts with: 0,1,1,..."
		// all other inputs
		} else {
			// start at the first index of fibArr (index 0). adjust stop condition on for loop to num -2, since fibArr is hard coded with first two values. the loop will generate exactly one value when num is 3, because it starts at 0 and runs once for that iteration, and stops after that. increment by 1 to generate each value
			for(i = 0; i < num - 2; i++) {
				// note: value on the left isn't yet defined; generate it and add it to the array
				// the value on the left is generated by adding the two previous values
				// this also means .push isnt needed, since js will add this value to the array by default
    		fibArr[fibArr.length] = fibArr[fibArr.length-1] + fibArr[fibArr.length-2];
			} // ends for loop
		} // ends else
	} // ends else
	// return the array with the new values
	return fibArr
} // ends function
