// check for empty numeric input field. set default value to 0 when no input value is present
const numInputs = document.querySelectorAll('input[type=number]');
numInputs.forEach(function (input) {
  input.addEventListener('change', function (e) {
    if (e.target.value == '') {
      e.target.value = 0
    }
  })
})

// run the function when the user clicks the button
document.getElementById('generate').onclick = function() {
	// initialize looping variable here. no recursion used to generate the fibonacci numbers
	var i, fibArr = [0,1];
	// save the input value from the dom. also need to convert the data type to number, even though the type in the markup is already a number, it gets converted to a string somewhere in the process
	var num = parseFloat(document.getElementById('user_pick').value);
	// any numeric input less than 3
	if (num < 3) {
		document.getElementById('result_message').innerHTML = "The Fibonacci sequence starts with: 0,1,1,...";
		// stop the function after the message is displayed in the dom
		return false
	// all other inputs
	} else {
		// start at the first index of fibArr (index 0). adjust stop condition on for loop to num -2, since fibArr is hard coded with first two values. the loop will generate exactly one value when num is 3, because it starts at 0 and runs once for that iteration, and stops after that. increment by 1 to generate each value
		for(i = 0; i < num - 2; i++) {
			// note: value on the left isn't yet defined; generate it and add it to the array
			// the value on the left is generated by adding the two previous values
			// this also means .push isnt needed, since js will add this value to the array by default
  		fibArr[fibArr.length] = fibArr[fibArr.length-1] + fibArr[fibArr.length-2];
		} // ends for loop
	} // ends else

	// clear any leftover result message from previous function calls
	document.getElementById('result_message').innerHTML = '';
	if(num === 3) {
		// get the last element of the newly appended fibArr array, display it in the dom
		document.getElementById('result_number').innerHTML = num + 'rd' + ' Fibonacci number is: ' + fibArr[fibArr.length-1];
		// get the entire array and display it in the dom
		document.getElementById('result_array').innerHTML = fibArr;
	} else {
		// get the last element of the newly appended fibArr array, display it in the dom
		document.getElementById('result_number').innerHTML = num + 'th' + ' Fibonacci number is: ' + fibArr[fibArr.length-1];
		// get the entire array and display it in the dom
		document.getElementById('result_array').innerHTML = '[' + fibArr + ']';
	} // ends else
} // ends function
